# Generated by Django 5.0.4 on 2024-07-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anggota', '0003_alter_anggota_options_alter_anggota_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('jenis', models.CharField(max_length=50)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_berakhir', models.DateField(blank=True, null=True)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
            ],
        ),
    ]
