# Generated by Django 5.0.4 on 2024-05-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
        ('simpanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpanan',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simpanan', to='anggota.anggota'),
        ),
    ]
