# Generated by Django 5.0.4 on 2024-07-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpanan', '0002_alter_simpanan_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpanan',
            name='jumlah_simpanan',
            field=models.CharField(max_length=100),
        ),
    ]
