# Generated by Django 5.0.4 on 2024-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anggota',
            options={'verbose_name': 'Anggota', 'verbose_name_plural': 'Anggota'},
        ),
        migrations.AlterField(
            model_name='anggota',
            name='email',
            field=models.EmailField(help_text='Alamat email harus unik', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='nomor_hp',
            field=models.CharField(help_text='Nomor HP harus unik', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='tanggal_lahir',
            field=models.DateField(help_text='Format: YYYY-MM-DD'),
        ),
    ]
