# Generated by Django 5.0.4 on 2024-05-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pinjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nomor_hp', models.CharField(max_length=15, unique=True)),
                ('jenis_simpanan', models.CharField(max_length=100)),
                ('jumlah_simpanan', models.DateField()),
                ('tanggal_simpanan', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
