# Generated by Django 5.0.4 on 2024-05-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjaman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinjaman',
            old_name='jumlah_simpanan',
            new_name='jangka_waktu',
        ),
        migrations.RenameField(
            model_name='pinjaman',
            old_name='jenis_simpanan',
            new_name='jumlah_pinjaman',
        ),
        migrations.RenameField(
            model_name='pinjaman',
            old_name='tanggal_simpanan',
            new_name='tanggal_pinjaman',
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='status_pinjaman',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
